export type OpCategory =
  | "input"
  | "output"
  | "conv"
  | "activation"
  | "normalization"
  | "pooling"
  | "reshape"
  | "math"
  | "reduction"
  | "merge"
  | "attention"
  | "recurrent"
  | "quantization"
  | "constant"
  | "logic"
  | "unknown";

const CATEGORY_MAP: Record<string, OpCategory> = {
  Input: "input",
  Output: "output",
  Conv: "conv",
  ConvTranspose: "conv",
  DepthwiseConv: "conv",
  Gemm: "math",
  MatMul: "math",
  Linear: "math",
  QLinearConv: "conv",
  QLinearMatMul: "math",
  Relu: "activation",
  Relu6: "activation",
  Sigmoid: "activation",
  Tanh: "activation",
  Softmax: "activation",
  LogSoftmax: "activation",
  Gelu: "activation",
  Silu: "activation",
  Elu: "activation",
  LeakyRelu: "activation",
  Selu: "activation",
  Mish: "activation",
  HardSwish: "activation",
  HardSigmoid: "activation",
  PRelu: "activation",
  Erf: "activation",
  BatchNormalization: "normalization",
  LayerNormalization: "normalization",
  GroupNormalization: "normalization",
  InstanceNormalization: "normalization",
  LpNormalization: "normalization",
  MeanVarianceNormalization: "normalization",
  MaxPool: "pooling",
  AveragePool: "pooling",
  GlobalAveragePool: "pooling",
  GlobalMaxPool: "pooling",
  LpPool: "pooling",
  MaxUnpool: "pooling",
  RoiAlign: "pooling",
  Reshape: "reshape",
  Flatten: "reshape",
  Squeeze: "reshape",
  Unsqueeze: "reshape",
  Transpose: "reshape",
  Expand: "reshape",
  Resize: "reshape",
  Upsample: "reshape",
  SpaceToDepth: "reshape",
  DepthToSpace: "reshape",
  PixelShuffle: "reshape",
  Pad: "reshape",
  Shape: "reshape",
  Slice: "reshape",
  Constant: "constant",
  ConstantOfShape: "constant",
  Add: "math",
  Sub: "math",
  Mul: "math",
  Div: "math",
  Pow: "math",
  Sqrt: "math",
  Exp: "math",
  Log: "math",
  Abs: "math",
  Neg: "math",
  Ceil: "math",
  Floor: "math",
  Round: "math",
  Sign: "math",
  Reciprocal: "math",
  Max: "math",
  Min: "math",
  Mod: "math",
  Clip: "math",
  Equal: "logic",
  Less: "logic",
  LessOrEqual: "logic",
  Greater: "logic",
  GreaterOrEqual: "logic",
  Not: "math",
  And: "math",
  Or: "math",
  Xor: "math",
  BitShift: "math",
  BitwiseAnd: "math",
  BitwiseOr: "math",
  BitwiseXor: "math",
  BitwiseNot: "math",
  ReduceMean: "reduction",
  ReduceSum: "reduction",
  ReduceMax: "reduction",
  ReduceMin: "reduction",
  ReduceProd: "reduction",
  ReduceL1: "reduction",
  ReduceL2: "reduction",
  ArgMax: "reduction",
  ArgMin: "reduction",
  CumSum: "reduction",
  Concat: "merge",
  Split: "merge",
  Gather: "merge",
  GatherElements: "merge",
  GatherND: "merge",
  Tile: "merge",
  ScatterElements: "merge",
  ScatterND: "merge",
  Where: "merge",
  NonZero: "reduction",
  TopK: "merge",
  MultiHeadAttention: "attention",
  Attention: "attention",
  EmbedLayerNormalization: "attention",
  SkipLayerNormalization: "attention",
  BiasGelu: "attention",
  LSTM: "recurrent",
  GRU: "recurrent",
  RNN: "recurrent",
  UnidirectionalSequenceLSTM: "recurrent",
  BidirectionalSequenceLSTM: "recurrent",
  BidirectionalSequenceRNN: "recurrent",
  QuantizeLinear: "quantization",
  DequantizeLinear: "quantization",
  DynamicQuantizeLinear: "quantization",

  // TFLite (UPPER_SNAKE_CASE)
  CONV_2D: "conv",
  DEPTHWISE_CONV_2D: "conv",
  TRANSPOSE_CONV: "conv",
  CONV_3D: "conv",
  CONV_3D_TRANSPOSE: "conv",
  FULLY_CONNECTED: "math",
  BATCH_MATMUL: "math",
  STABLEHLO_CONVOLUTION: "conv",
  STABLEHLO_DOT_GENERAL: "math",

  RELU: "activation",
  RELU6: "activation",
  RELU_N1_TO_1: "activation",
  RELU_0_TO_1: "activation",
  LOGISTIC: "activation",
  TANH: "activation",
  SOFTMAX: "activation",
  LOG_SOFTMAX: "activation",
  PRELU: "activation",
  LEAKY_RELU: "activation",
  ELU: "activation",
  HARD_SWISH: "activation",
  GELU: "activation",
  STABLEHLO_LOGISTIC: "activation",
  STABLEHLO_TANH: "activation",

  L2_NORMALIZATION: "normalization",
  LOCAL_RESPONSE_NORMALIZATION: "normalization",

  AVERAGE_POOL_2D: "pooling",
  MAX_POOL_2D: "pooling",
  L2_POOL_2D: "pooling",

  RESHAPE: "reshape",
  SQUEEZE: "reshape",
  EXPAND_DIMS: "reshape",
  TRANSPOSE: "reshape",
  RESIZE_BILINEAR: "reshape",
  RESIZE_NEAREST_NEIGHBOR: "reshape",
  SPACE_TO_DEPTH: "reshape",
  DEPTH_TO_SPACE: "reshape",
  SPACE_TO_BATCH_ND: "reshape",
  BATCH_TO_SPACE_ND: "reshape",
  PAD: "reshape",
  PADV2: "reshape",
  MIRROR_PAD: "reshape",
  BROADCAST_TO: "reshape",
  BROADCAST_ARGS: "reshape",
  SHAPE: "reshape",
  SLICE: "reshape",
  STRIDED_SLICE: "reshape",
  STABLEHLO_RESHAPE: "reshape",
  STABLEHLO_BROADCAST_IN_DIM: "reshape",
  STABLEHLO_SLICE: "reshape",

  ADD: "math",
  SUB: "math",
  MUL: "math",
  DIV: "math",
  ADD_N: "math",
  FLOOR: "math",
  CEIL: "math",
  ROUND: "math",
  NEG: "math",
  ABS: "math",
  SQRT: "math",
  RSQRT: "math",
  SQUARE: "math",
  EXP: "math",
  LOG: "math",
  SIN: "math",
  COS: "math",
  ATAN2: "math",
  POW: "math",
  SIGN: "math",
  MAXIMUM: "math",
  MINIMUM: "math",
  FLOOR_DIV: "math",
  FLOOR_MOD: "math",
  SQUARED_DIFFERENCE: "math",
  LOGICAL_AND: "math",
  LOGICAL_OR: "math",
  LOGICAL_NOT: "math",
  EQUAL: "math",
  NOT_EQUAL: "math",
  LESS: "math",
  LESS_EQUAL: "math",
  GREATER: "math",
  GREATER_EQUAL: "math",
  BITWISE_XOR: "math",
  RIGHT_SHIFT: "math",
  CAST: "math",
  BITCAST: "math",
  STABLEHLO_ADD: "math",
  STABLEHLO_SUBTRACT: "math",
  STABLEHLO_MULTIPLY: "math",
  STABLEHLO_DIVIDE: "math",
  STABLEHLO_MAXIMUM: "math",
  STABLEHLO_MINIMUM: "math",
  STABLEHLO_ABS: "math",
  STABLEHLO_NEGATE: "math",
  STABLEHLO_POWER: "math",
  STABLEHLO_REMAINDER: "math",
  STABLEHLO_RSQRT: "math",
  STABLEHLO_AND: "math",
  STABLEHLO_OR: "math",
  STABLEHLO_COMPARE: "math",
  STABLEHLO_COSINE: "math",
  STABLEHLO_EXPONENTIAL: "math",
  STABLEHLO_FLOOR: "math",
  STABLEHLO_LOG: "math",

  MEAN: "reduction",
  SUM: "reduction",
  REDUCE_PROD: "reduction",
  REDUCE_MAX: "reduction",
  REDUCE_MIN: "reduction",
  REDUCE_ANY: "reduction",
  REDUCE_ALL: "reduction",
  ARG_MAX: "reduction",
  ARG_MIN: "reduction",
  TOPK_V2: "reduction",
  CUMSUM: "reduction",
  SEGMENT_SUM: "reduction",
  UNSORTED_SEGMENT_PROD: "reduction",
  UNSORTED_SEGMENT_MAX: "reduction",
  UNSORTED_SEGMENT_SUM: "reduction",
  UNSORTED_SEGMENT_MIN: "reduction",
  STABLEHLO_REDUCE: "reduction",
  STABLEHLO_REDUCE_WINDOW: "reduction",

  CONCATENATION: "merge",
  SPLIT: "merge",
  SPLIT_V: "merge",
  GATHER: "merge",
  GATHER_ND: "merge",
  SCATTER_ND: "merge",
  TILE: "merge",
  PACK: "merge",
  UNPACK: "merge",
  SELECT: "merge",
  SELECT_V2: "merge",
  WHERE: "merge",
  ONE_HOT: "merge",
  REVERSE_V2: "merge",
  REVERSE_SEQUENCE: "merge",
  DYNAMIC_UPDATE_SLICE: "merge",
  STABLEHLO_SCATTER: "merge",
  STABLEHLO_SELECT: "merge",
  STABLEHLO_DYNAMIC_SLICE: "merge",
  STABLEHLO_DYNAMIC_UPDATE_SLICE: "merge",
  STABLEHLO_CONCATENATE: "merge",

  UNIDIRECTIONAL_SEQUENCE_LSTM: "recurrent",
  BIDIRECTIONAL_SEQUENCE_LSTM: "recurrent",
  UNIDIRECTIONAL_SEQUENCE_RNN: "recurrent",
  BIDIRECTIONAL_SEQUENCE_RNN: "recurrent",
  SVDF: "recurrent",

  QUANTIZE: "quantization",
  DEQUANTIZE: "quantization",
  FAKE_QUANT: "quantization",

  // Keras (class_name values)
  Conv1D: "conv",
  Conv2D: "conv",
  Conv3D: "conv",
  Conv1DTranspose: "conv",
  Conv2DTranspose: "conv",
  Conv3DTranspose: "conv",
  DepthwiseConv1D: "conv",
  DepthwiseConv2D: "conv",
  SeparableConv1D: "conv",
  SeparableConv2D: "conv",
  Dense: "math",

  Activation: "activation",
  ReLU: "activation",
  LeakyReLU: "activation",
  PReLU: "activation",
  ThresholdedReLU: "activation",

  UnitNormalization: "normalization",

  MaxPooling1D: "pooling",
  MaxPooling2D: "pooling",
  MaxPooling3D: "pooling",
  AveragePooling1D: "pooling",
  AveragePooling2D: "pooling",
  AveragePooling3D: "pooling",
  GlobalMaxPooling1D: "pooling",
  GlobalMaxPooling2D: "pooling",
  GlobalMaxPooling3D: "pooling",
  GlobalAveragePooling1D: "pooling",
  GlobalAveragePooling2D: "pooling",
  GlobalAveragePooling3D: "pooling",

  Permute: "reshape",
  RepeatVector: "reshape",
  ZeroPadding1D: "reshape",
  ZeroPadding2D: "reshape",
  ZeroPadding3D: "reshape",
  Cropping1D: "reshape",
  Cropping2D: "reshape",
  Cropping3D: "reshape",
  UpSampling1D: "reshape",
  UpSampling2D: "reshape",
  UpSampling3D: "reshape",

  Subtract: "math",
  Multiply: "math",
  Average: "math",
  Maximum: "math",
  Minimum: "math",
  Dot: "math",

  Concatenate: "merge",

  AdditiveAttention: "attention",

  // TF raw graph ops (SavedModel GraphDef nodes)
  BiasAdd: "math",
  AddV2: "math",
  Rsqrt: "math",
  RealDiv: "math",
  FloorMod: "math",
  MatrixBandPart: "math",
  Cast: "math",

  Const: "constant",
  VarHandleOp: "constant",
  ReadVariableOp: "constant",
  VariableV2: "constant",
  Range: "constant",
  Fill: "constant",
  ZerosLike: "constant",
  OnesLike: "constant",

  FusedBatchNorm: "normalization",
  FusedBatchNormV2: "normalization",
  FusedBatchNormV3: "normalization",

  MaxPool3D: "pooling",
  AvgPool: "pooling",
  AvgPool3D: "pooling",

  Identity: "reshape",
  StridedSlice: "reshape",
  ExpandDims: "reshape",
  Pack: "reshape",
  Unpack: "reshape",
  PadV2: "reshape",
  MirrorPad: "reshape",
  BroadcastTo: "reshape",
  CropAndResize: "reshape",

  ConcatV2: "merge",
  GatherV2: "merge",
  GatherNd: "merge",
  SplitV: "merge",
  ResourceGather: "merge",
  DynamicPartition: "merge",
  DynamicStitch: "merge",

  Sum: "reduction",
  Mean: "reduction",
  Prod: "reduction",

  Dropout: "activation",

  SimpleRNN: "recurrent",
  Bidirectional: "recurrent",
  TimeDistributed: "recurrent",
  ConvLSTM1D: "recurrent",
  ConvLSTM2D: "recurrent",
  ConvLSTM3D: "recurrent",
};

// aten / torch namespace ops (TorchScript: "aten::op/Overload", ExecuTorch: "aten::op.Overload")
const ATEN_MAP: Record<string, OpCategory> = {
  // conv
  conv1d: "conv",
  conv2d: "conv",
  conv3d: "conv",
  conv_transpose1d: "conv",
  conv_transpose2d: "conv",
  conv_transpose3d: "conv",
  conv_depthwise3d: "conv",
  convolution: "conv",
  _convolution: "conv",

  // math
  add: "math",
  add_: "math",
  sub: "math",
  sub_: "math",
  mul: "math",
  mul_: "math",
  div: "math",
  div_: "math",
  true_divide: "math",
  floor_divide: "math",
  remainder: "math",
  fmod: "math",
  pow: "math",
  sqrt: "math",
  rsqrt: "math",
  exp: "math",
  exp2: "math",
  log: "math",
  log2: "math",
  log10: "math",
  log1p: "math",
  abs: "math",
  neg: "math",
  sign: "math",
  ceil: "math",
  floor: "math",
  round: "math",
  trunc: "math",
  frac: "math",
  clamp: "math",
  clamp_: "math",
  clip: "math",
  clip_: "math",
  reciprocal: "math",
  addcmul: "math",
  addcdiv: "math",
  lerp: "math",
  max: "math",
  min: "math",
  maximum: "math",
  minimum: "math",
  sin: "math",
  cos: "math",
  tan: "math",
  asin: "math",
  acos: "math",
  atan: "math",
  atan2: "math",
  sinh: "math",
  cosh: "math",
  tanh: "math",
  sigmoid: "activation",
  linear: "math",
  matmul: "math",
  mm: "math",
  bmm: "math",
  addmm: "math",
  baddbmm: "math",
  dot: "math",
  mv: "math",
  outer: "math",
  einsum: "math",
  cross: "math",
  cumsum: "reduction",
  cumprod: "reduction",

  // activation
  relu: "activation",
  relu_: "activation",
  relu6: "activation",
  leaky_relu: "activation",
  leaky_relu_: "activation",
  prelu: "activation",
  elu: "activation",
  elu_: "activation",
  selu: "activation",
  celu: "activation",
  gelu: "activation",
  silu: "activation",
  silu_: "activation",
  mish: "activation",
  hardswish: "activation",
  hardswish_: "activation",
  hardsigmoid: "activation",
  hardtanh: "activation",
  hardtanh_: "activation",
  softmax: "activation",
  log_softmax: "activation",
  softplus: "activation",
  softshrink: "activation",
  tanhshrink: "activation",
  threshold: "activation",
  threshold_: "activation",

  // normalization
  batch_norm: "normalization",
  layer_norm: "normalization",
  group_norm: "normalization",
  instance_norm: "normalization",
  local_response_norm: "normalization",
  rms_norm: "normalization",
  norm: "normalization",
  renorm: "normalization",

  // pooling
  max_pool1d: "pooling",
  max_pool2d: "pooling",
  max_pool3d: "pooling",
  avg_pool1d: "pooling",
  avg_pool2d: "pooling",
  avg_pool3d: "pooling",
  adaptive_max_pool1d: "pooling",
  adaptive_max_pool2d: "pooling",
  adaptive_max_pool3d: "pooling",
  adaptive_avg_pool1d: "pooling",
  adaptive_avg_pool2d: "pooling",
  adaptive_avg_pool3d: "pooling",
  fractional_max_pool2d: "pooling",
  fractional_max_pool3d: "pooling",
  lp_pool1d: "pooling",
  lp_pool2d: "pooling",

  // reshape
  reshape: "reshape",
  view: "reshape",
  flatten: "reshape",
  squeeze: "reshape",
  squeeze_: "reshape",
  unsqueeze: "reshape",
  unsqueeze_: "reshape",
  transpose: "reshape",
  permute: "reshape",
  contiguous: "reshape",
  expand: "reshape",
  expand_as: "reshape",
  repeat: "reshape",
  reshape_as: "reshape",
  as_strided: "reshape",
  narrow: "reshape",
  slice: "reshape",
  select: "reshape",
  index_select: "reshape",
  pad: "reshape",
  constant_pad_nd: "reshape",
  reflection_pad1d: "reshape",
  reflection_pad2d: "reshape",
  replication_pad1d: "reshape",
  replication_pad2d: "reshape",
  replication_pad3d: "reshape",
  upsample_nearest1d: "reshape",
  upsample_nearest2d: "reshape",
  upsample_nearest3d: "reshape",
  upsample_bilinear2d: "reshape",
  upsample_bicubic2d: "reshape",
  upsample_linear1d: "reshape",
  upsample_trilinear3d: "reshape",
  interpolate: "reshape",
  pixel_shuffle: "reshape",
  pixel_unshuffle: "reshape",
  roll: "reshape",
  rot90: "reshape",
  flip: "reshape",
  fliplr: "reshape",
  flipud: "reshape",

  // reduction
  sum: "reduction",
  mean: "reduction",
  prod: "reduction",
  std: "reduction",
  var: "reduction",
  amax: "reduction",
  amin: "reduction",
  argmax: "reduction",
  argmin: "reduction",
  topk: "reduction",
  sort: "reduction",
  argsort: "reduction",
  all: "reduction",
  any: "reduction",
  count_nonzero: "reduction",
  logsumexp: "reduction",

  // merge / indexing
  cat: "merge",
  stack: "merge",
  hstack: "merge",
  vstack: "merge",
  dstack: "merge",
  chunk: "merge",
  split: "merge",
  tensor_split: "merge",
  unbind: "merge",
  gather: "merge",
  scatter: "merge",
  scatter_add: "merge",
  index: "merge",
  index_put: "merge",
  index_put_: "merge",
  masked_select: "merge",
  masked_fill: "merge",
  masked_fill_: "merge",
  where: "merge",
  nonzero: "merge",
  unique: "merge",
  embedding: "merge",
  embedding_bag: "merge",

  // recurrent
  lstm: "recurrent",
  lstm_cell: "recurrent",
  gru: "recurrent",
  gru_cell: "recurrent",
  rnn_tanh: "recurrent",
  rnn_relu: "recurrent",
  rnn_tanh_cell: "recurrent",
  rnn_relu_cell: "recurrent",

  // attention
  scaled_dot_product_attention: "attention",
  multi_head_attention_forward: "attention",

  // quantization
  quantize_per_tensor: "quantization",
  quantize_per_channel: "quantization",
  dequantize: "quantization",
  fake_quantize_per_tensor_affine: "quantization",
  fake_quantize_per_channel_affine: "quantization",

  // logic
  eq: "logic",
  ne: "logic",
  lt: "logic",
  le: "logic",
  gt: "logic",
  ge: "logic",
  logical_and: "logic",
  logical_or: "logic",
  logical_not: "logic",
  logical_xor: "logic",
  isnan: "logic",
  isinf: "logic",
  isfinite: "logic",

  // constant / creation
  zeros: "constant",
  zeros_like: "constant",
  ones: "constant",
  ones_like: "constant",
  full: "constant",
  full_like: "constant",
  arange: "constant",
  linspace: "constant",
  eye: "constant",
  empty: "constant",
  empty_like: "constant",
  rand: "constant",
  randn: "constant",
  randint: "constant",
  tensor: "constant",
  scalar_tensor: "constant",
  as_tensor: "constant",
  fill_: "constant",
  zero_: "constant",

  // regularization
  dropout: "activation",
  dropout_: "activation",
  alpha_dropout: "activation",
  feature_alpha_dropout: "activation",

  // shape queries
  size: "reshape",
  sizes: "reshape",
  dim: "reshape",
  ndim: "reshape",
  stride: "reshape",
  t: "reshape",
  to: "reshape",
  type_as: "reshape",
  clone: "reshape",
  detach: "reshape",
  detach_: "reshape",
  copy_: "reshape",

  // count / length
  numel: "reduction",
  len: "reduction",
  __len__: "reduction",
  item: "reduction",

  // indexing
  __getitem__: "merge",
  __setitem__: "merge",
};

/** Extracts the base op name from an aten namespace op (e.g. "aten::add.int" → "add"). Returns null for non-aten ops. */
export function opBase(opType: string): string | null {
  const sep = opType.indexOf("::");
  if (sep === -1) return null;
  const after = opType.slice(sep + 2);
  const end = after.search(/[./]/);
  return end === -1 ? after : after.slice(0, end);
}

function atenCategory(opType: string): OpCategory | null {
  const base = opBase(opType);
  return base != null ? (ATEN_MAP[base] ?? null) : null;
}

export function opCategory(opType: string): OpCategory {
  return CATEGORY_MAP[opType] ?? atenCategory(opType) ?? "unknown";
}
